name: Video Auto Uploader

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: pip install telethon PyGithub

    - name: Run Script
      env:
        # هذه المتغيرات يجب أن تكون موجودة في Settings -> Secrets في مستودعك
        TG_API_ID: ${{ secrets.TG_API_ID }}
        TG_API_HASH: ${{ secrets.TG_API_HASH }}
        TG_SESSION: ${{ secrets.TG_SESSION }}
        GH_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      run: python video_to_github.py
