name: Video Auto Uploader

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: pip install telethon PyGithub

    - name: Run Script
      env:
        # قمنا بتغيير الأسماء هنا لتطابق ما وضعته أنت في Secrets حرفياً
        TG_API_ID: ${{ secrets.API_ID }}
        TG_API_HASH: ${{ secrets.API_HASH }}
        TG_SESSION: ${{ secrets.SESSION_STRING }}
        GH_TOKEN: ${{ secrets.YOUR_GITHUB_TOKEN }}
      run: python video_to_github.py
